language: go

go:
- 1.11.x

env:
- GO111MODULE=on

install:
- go get -v ./...

script:
- "./_bin/test.sh"

before_deploy:
- "./_bin/build.sh darwin ${TRAVIS_TAG}"
- "./_bin/build.sh linux ${TRAVIS_TAG}"

deploy:
  provider: releases
  api_key:
    secure: fMLwBNtkH3exzslrQ2BPX8Avvdy2QHibM7xdPga0ZLbgKeZjg7TVhJIjJKCrc9nrxq/XsJivjw1J9jt8vgSOWDZHdmrfXy+ABESURtDeTVqlBT97F65humnHjEYwtbwOR1VqKfD7MqwRH6QIV+BHslGKMGJ1BrhfJPhMLczeUXqgAKQIus/1iE6zZQCfQszud6Gv//kPsX6WB5aXuLUN6wZoSIr3fOgdz2s68g9Zk7ZuKiE4mbNx0fiAKqG3YRD4A1/aqhpDXMF9CFS+DsWDKFtqNKjB8lf3J/mdSsRcJHeIg6eo91NC5Hj1lV4QSoL5pLhAEq4jyRkTcoscnUB6IKAKTWV6jfeqB5yAutu7IYWa8H/iHsaNAZO6HMHnCZT9x3qL8NES/6Z1D/g6sMBMdDoXJF0ZX4HNoaeRGjuxprFrU96Jzv/lmhZP1Mb+9DgHdoJMMryen5YSR0ciHUV+yMsxsmpJq7+JJZmvCIgN51RXzb538oFqgGB4k79vZTq6/2Elux9Ox8oJvi/GN3UstWCwMdVdJ+N2hsQL92PCzN8Kvb+crJ/ICl2TJJwypYqv/8nM94INSanV721TVKuF5Tu+mWMQqdGpFjNKCJvS444rBgbTUfX34AEFKImfBclTZrsBhVyXlhp2Y3Ll3In7hnLHJMR1VOudVq2R/b+UN2I=
  file: 
    - "lsh_darwin_$TRAVIS_TAG"
    - "lsh_linux_$TRAVIS_TAG"
  on:
    tags: true
